const fs=require('fs');
const path=require('path');
const src=fs.readFileSync(path.join(__dirname,'club-pulse.js'),'utf8');
let failed=0;
function check(name,ok){if(ok)console.log(`✓ ${name}`);else{console.error(`✗ ${name}`);failed++}}
check('launcher pins core to immutable commit',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-core.js'));
check('launcher uses core v2 local cache',src.includes('ClubPulseCore_v2.js')&&src.includes("CORE+'?v=core2'"));
check('launcher uses resilience v6 local cache',src.includes('ClubPulseResiliencePatch_v6.js'));
check('launcher fetch tag is resilience6',src.includes("'resilience6'"));
check('launcher pins resilience v6 commit',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5'));
check('launcher uses data policy v9 local cache',src.includes('ClubPulseDataPolicyPatch_v9.js'));
check('launcher fetch tag is data-policy9',src.includes("'data-policy9'"));
check('launcher pins data policy v9 commit',src.includes('e2ebcad939fa2409e41e7a20954e7b76e7dbc87e/scriptable/club-pulse-data-policy-patch.js'));
check('launcher uses premium visual v6 local cache',src.includes('ClubPulsePremiumVisualPatch_v6.js'));
check('launcher fetch tag is premium6',src.includes("'premium6'"));
check('launcher pins premium visual v6 commit',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-premium-visual-patch.js'));
check('launcher uses small presentation v11 local cache',src.includes('ClubPulseSmallPresentationPatch_v11.js'));
check('launcher fetch tag is small-presentation11',src.includes("'small-presentation11'"));
check('launcher pins small presentation v11 commit',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-small-presentation-patch.js'));
check('launcher uses canonical form system v1',src.includes('ClubPulseFormSystemPatch_v1.js')&&src.includes("'form-system1'"));
check('launcher pins canonical form system v1',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-form-system-patch.js'));
check('launcher uses Small UI unification v3',src.includes('ClubPulseSmallUIUnificationPatch_v3.js')&&src.includes("'small-ui-unification3'"));
check('launcher pins Small UI unification v3',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-small-ui-unification-patch.js'));
check('launcher uses Previous Result v2',src.includes('ClubPulsePreviousResultPatch_v2.js')&&src.includes("'previous-result2'"));
check('launcher pins Previous Result v2',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-previous-result-patch.js'));
check('launcher uses Medium Scale Unification v3',src.includes('ClubPulseMediumScaleUnificationPatch_v3.js')&&src.includes("'medium-scale-unification3'"));
check('launcher pins Medium Scale Unification v3',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-medium-scale-unification-patch.js'));
check('launcher uses wave2 clubs and themes v5',src.includes('ClubPulseWave2ClubsPatch_v1.js')&&src.includes("'wave2-clubs1'")&&src.includes('ClubPulseWave2ThemesPatch_v5.js')&&src.includes("'wave2-themes5'"));
check('launcher pins wave2 immutable commits',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-wave2-clubs-patch.js')&&src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-wave2-themes-patch.js'));
check('launcher uses wave3 Netherlands v2 cache',src.includes('ClubPulseWave3NetherlandsClubsPatch_v1.js')&&src.includes("'wave3-nl-clubs1'")&&src.includes('ClubPulseWave3NetherlandsPatch_v2.js')&&src.includes("'wave3-netherlands2'"));
check('launcher pins wave3 venue-audited immutable commit',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-wave3-netherlands-clubs-patch.js')&&src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-wave3-netherlands-patch.js'));
check('launcher uses wave4 Lens v1 caches',src.includes('ClubPulseWave4LensClubPatch_v1.js')&&src.includes("'wave4-lens-club1'")&&src.includes('ClubPulseWave4LensPatch_v1.js')&&src.includes("'wave4-lens1'"));
check('launcher pins wave4 Lens immutable commits',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-wave4-lens-club-patch.js')&&src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-wave4-lens-patch.js'));
check('launcher uses Premier League venue registry v1',src.includes('ClubPulsePremierLeagueVenuesPatch_v1.js')&&src.includes("'pl-venues1'"));
check('launcher pins Premier League venue registry v1',src.includes('309658e07c56f1932b49c2d19e35d2940b8773f5/scriptable/club-pulse-premier-league-venues-patch.js'));
check('wave4 registry injects before core parameter resolution',src.includes("c=c.slice(0,pk)+cr+'\\n'+ec+'\\n'+w2c+'\\n'+w3c+'\\n'+w4c+'\\n'+c.slice(pk)"));
check('Premier League venue registry runs after Wave4 and before form system',src.includes("+w4l+'\\n'+plv+'\\n'+fs"));
check('canonical form system runs immediately before Small UI unification',src.includes("+plv+'\\n'+fs+'\\n'+sui"));
check('Previous Result runs after Small UI unification',src.includes("+fs+'\\n'+sui+'\\n'+pr"));
check('Medium Scale Unification v3 runs last',src.includes("+sui+'\\n'+pr+'\\n'+msu,b="));
check('patch loader remains local-first',src.includes("if(F.fileExists(file)){let s=F.readString(file);if(s&&s.length>=min)return s}"));
check('launcher documents 44-club architecture',src.includes('Club Pulse 44-club runtime')&&src.includes('Wave 4 adds RC Lens')&&src.includes('Data Policy v9')&&src.includes('Premium Visual v6')&&src.includes('Small Presentation v11')&&src.includes('Wave 2 Theme v5')&&src.includes('Wave 3 Netherlands v2')&&src.includes('Premier League Venue Registry v1')&&src.includes('Canonical Form System v1')&&src.includes('Small UI Unification v3')&&src.includes('Previous Result v2')&&src.includes('Medium Scale Unification v3'));
if(failed){console.error(`\nLauncher version QA FAILED: ${failed}`);process.exit(1)}
console.log('\nClub Pulse 44-club launcher version QA PASSED');
